### PR TITLE
Fix Conditional jump or move depends on uninitialised value

### PR DESCRIPTION
**Pull request by sudo-panda**

### CODE REVIEW

**Comment by vgvassilev** [comment]
This looks good to me. Is that relevant also for upstream?

**Comment by sudo-panda** [comment]
> This looks good to me. Is that relevant also for upstream?

No it seems not. I will have check what is causing this only on our side tomorrow.

I cannot reproduce the isalnum one on my system either.

**Review by wlav — APPROVED** [review]
If that makes some code checking tool happy, I guess it's okay. However, there is no code path where this code can produce incorrect results.

**Comment by vgvassilev** [comment]
Should we assert if that’s a nullptr? Eg, is no codepath has changed it?

**Comment by wlav** [comment]
Not sure where that `assert` would go. It need not be a nullptr (it is uninitialized, after all), just that that call to `GetBuffer()` will set it and/or its output of `buflen` such that `para.fValue.fVoidp && buflen != 0` is never incorrect, even if `fVoidp` remains uninitialized (it can: there's an immediate return path in `GetBuffer()` in case of strings, which are never treated as buffers, where `buf` isn't set to `nullptr`).

Maybe the tool will be more happy if the predicate `para.fValue.fVoidp && buflen != 0` is replaced by `buflen != 0 && para.fValue.fVoidp`? Or it could even simply be `buflen != 0`.

**Comment by wlav** [comment]
But initializing is, as is done in this PR, is fine, too, of course.

**Pull request merged**
